spring.application.name=CoolMateShop
server.port=9090

# 1. Cấu hình kết nối CSDL SQL Server (Thay password tài khoản sa của bạn)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CoolMate_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cấu hình JPA / Hibernate
# Dùng 'validate' hoặc 'none' vì database đã được tạo hoàn chỉnh từ script SQL trước đó
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. Cấu hình upload file (Ảnh sản phẩm, feedback)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB